require('dotenv').config();

module.exports = {
  BOT_NAME: process.env.BOT_NAME || 'DENTSU MD V9',
  DEV_NAME: process.env.DEV_NAME || 'Natsu Tech',
  PREFIX: process.env.PREFIX || '.',
  PREFIXES: (process.env.PREFIXES || '.,!,/,#,$').split(',').map(p => p.trim()).filter(Boolean),
  MODE: process.env.MODE || 'public',
  OWNER_NUMBER: process.env.OWNER_NUMBER || '242065121108',
  BOT_FOOTER: process.env.BOT_FOOTER || '> 𝙼𝙰𝙳𝙴 𝙱𝚈 𝙽𝙰𝚃𝚂𝚄𝚘𝚛𝙳𝙴𝙽𝚃𝚂𝚄',
  PORT: parseInt(process.env.PORT) || 3000,
  SESSION_BASE_PATH: process.env.SESSION_BASE_PATH || './session',
  MAX_SESSIONS: parseInt(process.env.MAX_SESSIONS) || 50,
  AUTO_VIEW_STATUS: process.env.AUTO_VIEW_STATUS === 'true',
  AUTO_LIKE_STATUS: process.env.AUTO_LIKE_STATUS === 'true',
  AUTO_RECORDING: process.env.AUTO_RECORDING === 'true',
  AUTO_TYPING: process.env.AUTO_TYPING === 'true',
  AUTO_LIKE_EMOJI: ['💋','😶','✨️','💗','🎈','🎉','🥳','❤️','🧫','🐭'],
  MAX_RETRIES: 3,
  MENU_IMAGE: process.env.MENU_IMAGE || 'https://raw.githubusercontent.com/natsu242/DENTSU-MD-V9/main/assets/menu.png',
  RCD_IMAGE: process.env.RCD_IMAGE || 'https://files.catbox.moe/s1ggtt.jpeg',
  CHANNEL_LINK: process.env.CHANNEL_LINK || 'https://whatsapp.com/channel/0029VbC1s7fFnSz1YhZYc01h',
  CHANNEL_LINK2: 'https://whatsapp.com/channel/0029VayOeIbGufIvDPhi6m1X',
  GROUP_LINK: process.env.GROUP_LINK || 'https://chat.whatsapp.com/GtXASqDdchAFvEJ95cQQ0F',
  NEWSLETTER_JID: process.env.NEWSLETTER_JID || '120363423640959729@newsletter',
  WEBSITE: process.env.WEBSITE || 'https://dentsu-md-v9.onrender.com',
  TELEGRAM: process.env.TELEGRAM || 'https://t.me/Natsu_or_Dentsu',
  OTP_EXPIRY: 300000,
};
